# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlQ6fIPHTsIGDqEfzxJl_8AEJZYixY46
"""

def count_fail(score_list):
  total = 0
  for i in score_list:
    if int(i) <60:
      total += 1

  return total

score_list = input().split()
answer = count_fail(score_list)
print(answer)